class AddDefaultvaluesCsim < ActiveRecord::Migration
 	def self.up
		Course.create  id:'1', course_code: 'AT70.02',   coursename:'Computer Organization and Architecture',		credit:'3(3-0)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'2', course_code: 'AT70.02',	coursename:'Data Structures and Algorithms',			credit:'3(3-0)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'3', course_code: 'AT70.03',	coursename:'Theory of Computationgu',				credit:'3(3-0)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'4', course_code: 'AT70.04',	coursename:'Object-Oriented Analysis and Design',		credit:'3(2-3)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'5', course_code: 'AT70.05',	coursename:'Computer Networks', 				credit:'3(3-0)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'6', course_code: 'AT70.06',	coursename:'Java Technologies',					credit:'3(2-3)',	offered_sem:'August/Intersem',		department_id:'1'
		Course.create  id:'7', course_code: 'AT70.07',	coursename:'Programming Languages and Compilers',		credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'8', course_code: 'AT70.08',	coursename:'Operating Systems',					credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'9', course_code: 'AT70.09',	coursename:'Computer Graphics and Animation',			credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'10', course_code: 'AT70.11',	coursename:'Personalization in E-Business',			credit:'3(3-0)',	offered_sem:'January/Intersem',		department_id:'1'
		Course.create  id:'11', course_code: 'AT70.12',	coursename:'Web Technologies',					credit:'3(2-3)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'12', course_code: 'AT70.13',	coursename:'Computer Security',					credit:'3(3-0)',	offered_sem:'January/June Intersem',	department_id:'1'
		Course.create  id:'13', course_code: 'AT70.14',	coursename:'Managing Information Technology',			credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'14', course_code: 'AT70.15',	coursename:'Advanced Topics in Internet Technology',		credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'15', course_code: 'AT70.16',	coursename:'Computational Geometry and Applications',		credit:'3(3-0)',	offered_sem:'January/June Intersem',	department_id:'1'
		Course.create  id:'16', course_code: 'AT70.19',	coursename:'Software Development and Quality Improvement',	credit:'3(2-3)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'17', course_code: 'AT70.90',	coursename:'Network and Service management',			credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'18', course_code: 'AT71.01',	coursename:'Database Design',					credit:'3(3-0)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'19', course_code: 'AT71.02',	coursename:'Knowledge Management and Information Retrieval',	credit:'3(3-0)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'20', course_code: 'AT71.03',	coursename:'E-Business Development and Technology',		credit:'3(3-0)',	offered_sem:'August',			department_id:'1'
		Course.create  id:'21', course_code: 'AT71.04',	coursename:'Decision Support Technologies',			credit:'3(2-3)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'22', course_code: 'AT71.05',	coursename:'Information Systems Development',			credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'23', course_code: 'AT70.10',	coursename:'Paradigms of Artificial Intelligence',		credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'24', course_code: 'AT70.17',	coursename:'XML: Foundations, Techniques and Applications',	credit:'3(3-0)',	offered_sem:'January',			department_id:'1'
		Course.create  id:'25', course_code: 'AT70.18',	coursename:'Software Architecture I',				credit:'1(1-0)',	offered_sem:'August',			department_id:'1'		
		Course.create  id:'26', course_code: 'AT71.06',	coursename:'Human-Computer Interaction',			credit:'3(2-3)',	offered_sem:'January',			department_id:'1'
	end 
end
