class AddDefaultvaluesSchoolDepartment < ActiveRecord::Migration
  def self.up
	School.create id:'1', schoolname: 'School of Engineering and Technology', description: ''
	School.create id:'2', schoolname: 'School of Environment, Resources and Development', description: ''
	School.create id:'3', schoolname: 'School of Management', description: ''

	Department.create id:'1',  departmentname:'Computer Science and Information Management',		school_id:'1',        dep_code:'CSIM' 
	Department.create id:'2',  departmentname:'Remote Sensing and Geographic Information Systems',		school_id:'1',        dep_code:'RS-GIS'
	Department.create id:'3',  departmentname:'Telecommunications',						school_id:'1',        dep_code:'TC'
	Department.create id:'4',  departmentname:'Construction, Engineering and Infrastructure Management',	school_id:'1',        dep_code:'CEIM'
	Department.create id:'5',  departmentname:'Geotechnical and Earth Resources Engineering',		school_id:'1',        dep_code:'GTE'
	Department.create id:'6',  departmentname:'Geosystem Exploration and Petroleum GeoEngineering',		school_id:'1',        dep_code:'GEPG'
	Department.create id:'7',  departmentname:'Structural Engineering',					school_id:'1',        dep_code:'STE'
	Department.create id:'8',  departmentname:'Transportation Engineering',					school_id:'1',        dep_code:'TRE'
	Department.create id:'9',  departmentname:'Water Engineering and Management',				school_id:'1',        dep_code:'WEM'
	Department.create id:'10', departmentname:'Mechatronics',						school_id:'1',        dep_code:'MEC'
	Department.create id:'11', departmentname:'Microelectronics and Embedded Systems',			school_id:'1',        dep_code:'MES'
	Department.create id:'12', departmentname:'Industrial and Manufacturing Engineering',			school_id:'1',        dep_code:'IME'
	Department.create id:'13', departmentname:'NanoTechnology',						school_id:'1',        dep_code:'NT'
	Department.create id:'14', departmentname:'Offshore Technology and Management',				school_id:'1',        dep_code:'OTM'
	Department.create id:'15', departmentname:'Information and Communications Technologies',		school_id:'1',        dep_code:'ICT'
	Department.create id:'16', departmentname:'Disaster Preparedness, Mitigation and Management',		school_id:'1',	 dep_code:'DPMM'	
	Department.create id:'17',  departmentname:'Agri-Business Management',					school_id:'2',        dep_code:'ABM'
	Department.create id:'18',  departmentname:'Agricultural Systems and Engineering',			school_id:'2',        dep_code:'ASE'
	Department.create id:'19',  departmentname:'Aquaculture and Aquatic Resources Management',		school_id:'2',        dep_code:'AARM'
	Department.create id:'20',  departmentname:'Climate Change And Sustainable Development'	,		school_id:'2',        dep_code:'CCSD'
	Department.create id:'21',  departmentname:'Energy',							school_id:'2',        dep_code:'Energy'
	Department.create id:'22',  departmentname:'Environmental Engineering and Management',			school_id:'2',        dep_code:'EEM'
	Department.create id:'23',  departmentname:'Food Engineering and Bioprocess Technology',		school_id:'2',        dep_code:'FEBT'
	Department.create id:'24',  departmentname:'Gender And Development Studies',				school_id:'2',        dep_code:'GDS'
	Department.create id:'25',  departmentname:'Natural Resources Management',				school_id:'2',        dep_code:'NRM'
	Department.create id:'26',  departmentname:'Pulp And Paper Technology',					school_id:'2',        dep_code:'PPT'
	Department.create id:'27',  departmentname:'Regional And Rural Development Planning',			school_id:'2',        dep_code:'RRDP'
	Department.create id:'28',  departmentname:'Urban Environmental Management',				school_id:'2',        dep_code:'URM'
	Department.create id:'29',  departmentname:'Urban Water Engineering and Management',			school_id:'2',        dep_code:'UWEM'
	Department.create id:'30',  departmentname:'Master of Business Administration',				school_id:'3',        dep_code:'MBA'
	Department.create id:'31',  departmentname:'MBA in Energy Business',					school_id:'3',        dep_code:'MBA(EB)'
  end
end
